name: Update flake inputs
on:
  schedule:
    - cron: "0 7 * * *" # Run every day at 7AM

permissions:
  pull-requests: write
  contents: write
  checks: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.11

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: Update Flake
        run: |
          nix flake update
          nix develop --command bash -c "echo \"This is here so that the sync-npm-git-dependencies-with-nix runs\""

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            package_json:
              - '**/*/package.json'

      - name: Create Pull Request
        id: cpr
        if: steps.changes.outputs.flake_lock == 'true' || steps.changes.outputs.package_json == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PULL_REQUESTS_ENABLE_CHECKS_TOKEN }}

      - name: Enable Pull Request Automerge
        if: (steps.changes.outputs.flake_lock == 'true' || steps.changes.outputs.package_json == 'true') && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PULL_REQUESTS_ENABLE_CHECKS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
